// This file exports product categories as an array of objects for easy API replacement later
export const productCategories = [
  { name: 'Ceiling Luminaires', href: '/products/ceiling-luminaires' },
  { name: 'Surface Luminaires', href: '/products/surface-luminaires' },
  { name: 'Panel Luminaires', href: '/products/panel-luminaires' },
  { name: 'Bulbs', href: '/products/bulbs' },
  { name: 'Battens', href: '/products/battens' },
  { name: 'Wall Luminaires', href: '/products/wall-luminaires' },
  { name: 'Bulkheads', href: '/products/bulkheads' },
  { name: 'CoB Luminaires', href: '/products/cob-luminaires' },
  { name: 'Mirror Luminaires', href: '/products/mirror-luminaires' },
  { name: 'Cabinet Luminaires', href: '/products/cabinet-luminaires' },
  { name: 'Smart Luminaires', href: '/products/smart-luminaires' },
  { name: 'Emergency_Inverter Luminaires', href: '/products/emergency-inverter-luminaires' },
  { name: 'Facade Luminaires', href: '/products/facade-luminaires' },
  { name: 'Road Luminaires', href: '/products/road-luminaires' },
  { name: 'Flood_High Mast Luminaires', href: '/products/flood-high-mast-luminaires' },
  { name: 'High-Bay Luminaires', href: '/products/high-bay-luminaires' },
  { name: 'Flame Proof Luminaires', href: '/products/flame-proof-luminaires' },
  { name: 'Bollards', href: '/products/bollards' },
  { name: 'Post Top Lanterns', href: '/products/post-top-lanterns' },
  { name: 'Swimming Pool Luminaires', href: '/products/swimming-pool-luminaires' },
  { name: 'Designer Poles & Furniture', href: '/products/designer-poles-furniture' },
  { name: 'Footer', href: '/products/footer' },
];
export const solarCategories = [
    { name: 'Solar Street Lights', href: '/solar/street-lights' },
    { name: 'Semi-Integrated', href: '/solar/semi-integrated' },
    { name: 'All-in-One', href: '/solar/all-in-one' },
    { name: 'Hybrid', href: '/solar/hybrid' },
    { name: 'Solar Mini Mast', href: '/solar/mini-mast' },
    { name: 'Solar High mast', href: '/solar/high-mast' },
    { name: 'Solar CCTV Cameras', href: '/solar/cctv-cameras' },
    { name: 'Solar Traffic Blinkers', href: '/solar/traffic-blinkers' },
    { name: 'Solar Mobile Lighting Towers', href: '/solar/mobile-lighting-towers' },
];

export const solutionCategories = [
    { name: 'Residential & Apartments', href: '/solutions/residential-apartments' },
    { name: 'Offices (Banks, Hotels, Hospitals & Schools)', href: '/solutions/offices' },
    { name: 'Retail & Museums', href: '/solutions/retail-museums' },
    { name: 'Pharma, Operation theaters and Cold Storages', href: '/solutions/pharma-cold-storage' },
    { name: 'Entertainment & Sports', href: '/solutions/entertainment-sports' },
    { name: 'Ports and SEZs', href: '/solutions/ports-sezs' },
    { name: 'Airports, Metros and Railway Stations', href: '/solutions/airports-metros-railways' },
    { name: 'Industrial and Warehouses', href: '/solutions/industrial-warehouses' },
    { name: 'Architectural Monuments', href: '/solutions/architectural-monuments' },
    { name: 'Landscape', href: '/solutions/landscape' },
    { name: 'Swimming Pools', href: '/solutions/swimming-pools' },
    { name: 'Emergency & Exits', href: '/solutions/emergency-exits' },
];
